font:
  normal:
    family: 'DejaVuSansM Nerd Font Propo'
    style: Regular
  bold:
    family: 'DejaVuSansM Nerd Font Propo'
    style: Bold
  italic:
    family: 'DejaVuSansM Nerd Font Propo'
    style: Oblique
  bold_italic:
    family: 'DejaVuSansM Nerd Font Propo'
    style: 'Bold Oblique'
  size: 14.0

mouse:
  hide_when_typing: true

selection:
  # Characters that are used as separators for "semantic words" 
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

draw_bold_text_with_bright_colors: true

colors:
  # Gruvbox
  primary:
    background: '0x282828'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
